import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from "react";

export default function Home() {
  const [ws, setWs] = useState(null);
  const [message, setMessage] = useState('');
  const [chat, setChat] = useState([]);

  useEffect(() => {
    const newWs = new WebSocket('ws://localhost:8000/ws');
    newWs.onopen = () => console.log('WebSocket connected');
    newWs.onmessage = (event) => {
      const receivedMessage = JSON.parse(event.data);
      console.log(receivedMessage);
      setChat((prevChat) => [...prevChat, receivedMessage]);
    };
    setWs(newWs);

    return () => {
      newWs.close();
    };
  }, []);

  const sendMessage = () => {
    if (ws && message.trim() !== '') {
      const msg = { // Data yang dikirim
        username: 'User',
        text: message,
      };
      ws.send(JSON.stringify(msg));
      setMessage('');
    }
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="App">
          <h1>Socket.IO Chat App</h1>
          <div className="chat-container">
            <div className="chat-messages">
              {chat.map((msg, index) => (
                  <div key={index} className="message">
                    {msg.username} - {msg.text}
                  </div>
              ))}
            </div>
            <div className="chat-input">
              <input
                  type="text"
                  placeholder="Enter your message..."
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
              />
              <button onClick={sendMessage}>Send</button>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
